Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,11 +15,7 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v3
-        with:
-          python-version: ${{ matrix.python-version }}
-      - name: Install wheel package
+      - name: install wheel package
         run: |
           /opt/python/cp39-cp39/bin/pip install --upgrade --no-cache-dir pip
           /opt/python/cp39-cp39/bin/pip install --no-cache-dir wheel
@@ -45,9 +41,11 @@ jobs:
           ENABLE_JAVA: 0
           ENABLE_CONTRIB: 0
           ENABLE_GUI: 0
+          PYTHON3_EXECUTABLE: "/opt/python/cp39-cp39/bin/python"
         run: |
           cd opencv
           /opt/python/cp39-cp39/bin/python setup.py bdist_wheel --verbose
+          find . -type f -iregex ".*-[manylinux|linux].*\.whl" -exec bash -c "auditwheel repair '{}' -w \$(dirname '{}') --plat 'manylinux2014_x86_64' || { echo 'Repairing wheels failed.'; auditwheel show '{}' &>> "$failed_wheels"; }" \;
       - run: ls -l opencv/dist
       - name: upload wheel
         uses: actions/upload-artifact@v3
